<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_pja extends CI_Migration {

  function up () {

    $this->db->query("
      CREATE TABLE `pja` (
        `uuid` varchar(36) NOT NULL,
        `orders` INT(11) UNIQUE NOT NULL AUTO_INCREMENT,
        `acceptedAt` datetime DEFAULT NULL,
        `createdAt` datetime DEFAULT NULL,
        `updatedAt` datetime DEFAULT NULL,
        `project` varchar(36) NOT NULL,
        `progress` INT(11) NOT NULL,
        `lock` TINYINT(1) NOT NULL,
        `1a_isneed` TINYINT(1) NOT NULL,
        `1a_isya` TINYINT(1) NOT NULL,
        `1a_note` varchar(255) NOT NULL,
        `1b_isneed` TINYINT(1) NOT NULL,
        `1b_isya` TINYINT(1) NOT NULL,
        `1b_note` varchar(255) NOT NULL,
        `2a_isneed` TINYINT(1) NOT NULL,
        `2a_isya` TINYINT(1) NOT NULL,
        `2a_note` varchar(255) NOT NULL,
        `2b_isneed` TINYINT(1) NOT NULL,
        `2b_isya` TINYINT(1) NOT NULL,
        `2b_note` varchar(255) NOT NULL,
        `2c_isneed` TINYINT(1) NOT NULL,
        `2c_isya` TINYINT(1) NOT NULL,
        `2c_note` varchar(255) NOT NULL,
        `2d_isneed` TINYINT(1) NOT NULL,
        `2d_isya` TINYINT(1) NOT NULL,
        `2d_note` varchar(255) NOT NULL,
        `3a_isneed` TINYINT(1) NOT NULL,
        `3a_isya` TINYINT(1) NOT NULL,
        `3a_note` varchar(255) NOT NULL,
        `3b_isneed` TINYINT(1) NOT NULL,
        `3b_isya` TINYINT(1) NOT NULL,
        `3b_note` varchar(255) NOT NULL,
        `3c_isneed` TINYINT(1) NOT NULL,
        `3c_isya` TINYINT(1) NOT NULL,
        `3c_note` varchar(255) NOT NULL,
        `3d_isneed` TINYINT(1) NOT NULL,
        `3d_isya` TINYINT(1) NOT NULL,
        `3d_note` varchar(255) NOT NULL,
        `3e_isneed` TINYINT(1) NOT NULL,
        `3e_isya` TINYINT(1) NOT NULL,
        `3e_note` varchar(255) NOT NULL,
        `3f_isneed` TINYINT(1) NOT NULL,
        `3f_isya` TINYINT(1) NOT NULL,
        `3f_note` varchar(255) NOT NULL,
        `4a_isneed` TINYINT(1) NOT NULL,
        `4a_isya` TINYINT(1) NOT NULL,
        `4a_note` varchar(255) NOT NULL,
        `4b_isneed` TINYINT(1) NOT NULL,
        `4b_isya` TINYINT(1) NOT NULL,
        `4b_note` varchar(255) NOT NULL,
        `4c_isneed` TINYINT(1) NOT NULL,
        `4c_isya` TINYINT(1) NOT NULL,
        `4c_note` varchar(255) NOT NULL,
        `4d_isneed` TINYINT(1) NOT NULL,
        `4d_isya` TINYINT(1) NOT NULL,
        `4d_note` varchar(255) NOT NULL,
        `4e_isneed` TINYINT(1) NOT NULL,
        `4e_isya` TINYINT(1) NOT NULL,
        `4e_note` varchar(255) NOT NULL,
        `5a_isneed` TINYINT(1) NOT NULL,
        `5a_isya` TINYINT(1) NOT NULL,
        `5a_note` varchar(255) NOT NULL,
        `5b_isneed` TINYINT(1) NOT NULL,
        `5b_isya` TINYINT(1) NOT NULL,
        `5b_note` varchar(255) NOT NULL,
        `5c_isneed` TINYINT(1) NOT NULL,
        `5c_isya` TINYINT(1) NOT NULL,
        `5c_note` varchar(255) NOT NULL,
        `5d_isneed` TINYINT(1) NOT NULL,
        `5d_isya` TINYINT(1) NOT NULL,
        `5d_note` varchar(255) NOT NULL,
        `6a_isneed` TINYINT(1) NOT NULL,
        `6a_isya` TINYINT(1) NOT NULL,
        `6a_note` varchar(255) NOT NULL,
        `6b_isneed` TINYINT(1) NOT NULL,
        `6b_isya` TINYINT(1) NOT NULL,
        `6b_note` varchar(255) NOT NULL,
        `6c_isneed` TINYINT(1) NOT NULL,
        `6c_isya` TINYINT(1) NOT NULL,
        `6c_note` varchar(255) NOT NULL,
        `6d_isneed` TINYINT(1) NOT NULL,
        `6d_isya` TINYINT(1) NOT NULL,
        `6d_note` varchar(255) NOT NULL,
        `7a_isneed` TINYINT(1) NOT NULL,
        `7a_isya` TINYINT(1) NOT NULL,
        `7a_note` varchar(255) NOT NULL,
        `7b_isneed` TINYINT(1) NOT NULL,
        `7b_isya` TINYINT(1) NOT NULL,
        `7b_note` varchar(255) NOT NULL,
        `8a_isneed` TINYINT(1) NOT NULL,
        `8a_isya` TINYINT(1) NOT NULL,
        `8a_note` varchar(255) NOT NULL,
        `8b_isneed` TINYINT(1) NOT NULL,
        `8b_isya` TINYINT(1) NOT NULL,
        `8b_note` varchar(255) NOT NULL,
        `8c_isneed` TINYINT(1) NOT NULL,
        `8c_isya` TINYINT(1) NOT NULL,
        `8c_note` varchar(255) NOT NULL,
        `8d_isneed` TINYINT(1) NOT NULL,
        `8d_isya` TINYINT(1) NOT NULL,
        `8d_note` varchar(255) NOT NULL,
        `8e_isneed` TINYINT(1) NOT NULL,
        `8e_isya` TINYINT(1) NOT NULL,
        `8e_note` varchar(255) NOT NULL,
        `8f_isneed` TINYINT(1) NOT NULL,
        `8f_isya` TINYINT(1) NOT NULL,
        `8f_note` varchar(255) NOT NULL,
        `8g_isneed` TINYINT(1) NOT NULL,
        `8g_isya` TINYINT(1) NOT NULL,
        `8g_note` varchar(255) NOT NULL,
        `9a_isneed` TINYINT(1) NOT NULL,
        `9a_isya` TINYINT(1) NOT NULL,
        `9a_note` varchar(255) NOT NULL,
        `9b_isneed` TINYINT(1) NOT NULL,
        `9b_isya` TINYINT(1) NOT NULL,
        `9b_note` varchar(255) NOT NULL,
        `9c_isneed` TINYINT(1) NOT NULL,
        `9c_isya` TINYINT(1) NOT NULL,
        `9c_note` varchar(255) NOT NULL,
        `9d_isneed` TINYINT(1) NOT NULL,
        `9d_isya` TINYINT(1) NOT NULL,
        `9d_note` varchar(255) NOT NULL,
        `9e_isneed` TINYINT(1) NOT NULL,
        `9e_isya` TINYINT(1) NOT NULL,
        `9e_note` varchar(255) NOT NULL,
        `10a_isneed` TINYINT(1) NOT NULL,
        `10a_isya` TINYINT(1) NOT NULL,
        `10a_note` varchar(255) NOT NULL,
        `10b_isneed` TINYINT(1) NOT NULL,
        `10b_isya` TINYINT(1) NOT NULL,
        `10b_note` varchar(255) NOT NULL,
        `10c_isneed` TINYINT(1) NOT NULL,
        `10c_isya` TINYINT(1) NOT NULL,
        `10c_note` varchar(255) NOT NULL,
        `10d_isneed` TINYINT(1) NOT NULL,
        `10d_isya` TINYINT(1) NOT NULL,
        `10d_note` varchar(255) NOT NULL,
        `10e_isneed` TINYINT(1) NOT NULL,
        `10e_isya` TINYINT(1) NOT NULL,
        `10e_note` varchar(255) NOT NULL,
        `10f_isneed` TINYINT(1) NOT NULL,
        `10f_isya` TINYINT(1) NOT NULL,
        `10f_note` varchar(255) NOT NULL,
        `11a_isneed` TINYINT(1) NOT NULL,
        `11a_isya` TINYINT(1) NOT NULL,
        `11a_note` varchar(255) NOT NULL,
        `11b_isneed` TINYINT(1) NOT NULL,
        `11b_isya` TINYINT(1) NOT NULL,
        `11b_note` varchar(255) NOT NULL,
        `12a_isneed` TINYINT(1) NOT NULL,
        `12a_isya` TINYINT(1) NOT NULL,
        `12a_note` varchar(255) NOT NULL,
        `12b_isneed` TINYINT(1) NOT NULL,
        `12b_isya` TINYINT(1) NOT NULL,
        `12b_note` varchar(255) NOT NULL,
        `12c_isneed` TINYINT(1) NOT NULL,
        `12c_isya` TINYINT(1) NOT NULL,
        `12c_note` varchar(255) NOT NULL,
        `12d_isneed` TINYINT(1) NOT NULL,
        `12d_isya` TINYINT(1) NOT NULL,
        `12d_note` varchar(255) NOT NULL,
        PRIMARY KEY (`uuid`),
        KEY `project` (`project`)
      ) ROW_FORMAT=DYNAMIC ENGINE=InnoDB DEFAULT CHARSET=utf8
    ");

  }

  function down () {
    $this->db->query("DROP TABLE IF EXISTS `pja`");
  }

}