<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_kpi extends CI_Migration {

  function up () {

    $this->db->query("
      CREATE TABLE `kpi` (
        `uuid` varchar(36) NOT NULL,
        `orders` INT(11) UNIQUE NOT NULL AUTO_INCREMENT,
        `acceptedAt` datetime DEFAULT NULL,
        `createdAt` datetime DEFAULT NULL,
        `updatedAt` datetime DEFAULT NULL,
        `project` varchar(36) NOT NULL,
        `progress` INT(11) NOT NULL,
        `lock` TINYINT(1) NOT NULL,
        `a1_target` TINYINT(1) NOT NULL,
        `a1_actual` TINYINT(1) NOT NULL,
        `a1_score_max` TINYINT(1) NOT NULL,
        `a1_score_actual` TINYINT(1) NOT NULL,
        `a1_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `a2_target` TINYINT(1) NOT NULL,
        `a2_actual` TINYINT(1) NOT NULL,
        `a2_score_max` TINYINT(1) NOT NULL,
        `a2_score_actual` TINYINT(1) NOT NULL,
        `a2_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `b1_target` TINYINT(1) NOT NULL,
        `b1_actual` TINYINT(1) NOT NULL,
        `b1_score_max` TINYINT(1) NOT NULL,
        `b1_score_actual` TINYINT(1) NOT NULL,
        `b1_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `b2_target` TINYINT(1) NOT NULL,
        `b2_actual` TINYINT(1) NOT NULL,
        `b2_score_max` TINYINT(1) NOT NULL,
        `b2_score_actual` TINYINT(1) NOT NULL,
        `b2_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `b3_target` TINYINT(1) NOT NULL,
        `b3_actual` TINYINT(1) NOT NULL,
        `b3_score_max` TINYINT(1) NOT NULL,
        `b3_score_actual` TINYINT(1) NOT NULL,
        `b3_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `b4_target` TINYINT(1) NOT NULL,
        `b4_actual` TINYINT(1) NOT NULL,
        `b4_score_max` TINYINT(1) NOT NULL,
        `b4_score_actual` TINYINT(1) NOT NULL,
        `b4_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `b5_target` TINYINT(1) NOT NULL,
        `b5_actual` TINYINT(1) NOT NULL,
        `b5_score_max` TINYINT(1) NOT NULL,
        `b5_score_actual` TINYINT(1) NOT NULL,
        `b5_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c1_target` TINYINT(1) NOT NULL,
        `c1_actual` TINYINT(1) NOT NULL,
        `c1_score_max` TINYINT(1) NOT NULL,
        `c1_score_actual` TINYINT(1) NOT NULL,
        `c1_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c2_target` TINYINT(1) NOT NULL,
        `c2_actual` TINYINT(1) NOT NULL,
        `c2_score_max` TINYINT(1) NOT NULL,
        `c2_score_actual` TINYINT(1) NOT NULL,
        `c2_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c3_target` TINYINT(1) NOT NULL,
        `c3_actual` TINYINT(1) NOT NULL,
        `c3_score_max` TINYINT(1) NOT NULL,
        `c3_score_actual` TINYINT(1) NOT NULL,
        `c3_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c4_target` TINYINT(1) NOT NULL,
        `c4_actual` TINYINT(1) NOT NULL,
        `c4_score_max` TINYINT(1) NOT NULL,
        `c4_score_actual` TINYINT(1) NOT NULL,
        `c4_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c5_target` TINYINT(1) NOT NULL,
        `c5_actual` TINYINT(1) NOT NULL,
        `c5_score_max` TINYINT(1) NOT NULL,
        `c5_score_actual` TINYINT(1) NOT NULL,
        `c5_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c6_target` TINYINT(1) NOT NULL,
        `c6_actual` TINYINT(1) NOT NULL,
        `c6_score_max` TINYINT(1) NOT NULL,
        `c6_score_actual` TINYINT(1) NOT NULL,
        `c6_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c7_target` TINYINT(1) NOT NULL,
        `c7_actual` TINYINT(1) NOT NULL,
        `c7_score_max` TINYINT(1) NOT NULL,
        `c7_score_actual` TINYINT(1) NOT NULL,
        `c7_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c8_target` TINYINT(1) NOT NULL,
        `c8_actual` TINYINT(1) NOT NULL,
        `c8_score_max` TINYINT(1) NOT NULL,
        `c8_score_actual` TINYINT(1) NOT NULL,
        `c8_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c9_target` TINYINT(1) NOT NULL,
        `c9_actual` TINYINT(1) NOT NULL,
        `c9_score_max` TINYINT(1) NOT NULL,
        `c9_score_actual` TINYINT(1) NOT NULL,
        `c9_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c10_target` TINYINT(1) NOT NULL,
        `c10_actual` TINYINT(1) NOT NULL,
        `c10_score_max` TINYINT(1) NOT NULL,
        `c10_score_actual` TINYINT(1) NOT NULL,
        `c10_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c11_target` TINYINT(1) NOT NULL,
        `c11_actual` TINYINT(1) NOT NULL,
        `c11_score_max` TINYINT(1) NOT NULL,
        `c11_score_actual` TINYINT(1) NOT NULL,
        `c11_doc` TINYINT(1) NOT NULL DEFAULT 0,
        `c12_target` TINYINT(1) NOT NULL,
        `c12_actual` TINYINT(1) NOT NULL,
        `c12_score_max` TINYINT(1) NOT NULL,
        `c12_score_actual` TINYINT(1) NOT NULL,
        `c12_doc` TINYINT(1) NOT NULL DEFAULT 0,
        PRIMARY KEY (`uuid`),
        KEY `project` (`project`)
      ) ROW_FORMAT=DYNAMIC ENGINE=InnoDB DEFAULT CHARSET=utf8
    ");

  }

  function down () {
    $this->db->query("DROP TABLE IF EXISTS `kpi`");
  }

}